name: CI

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Scala (JVM)
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:21

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}

      - name: Run tests
        run: sbt test
        
      - name: Run coverage
        run: sbt coverage test

      - name: Coverage report
        run: sbt coverageReport

      - name: Generate coverage XML
        run: sbt coverageAggregate

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: target/scala-3.*/scoverage-report/scoverage.xml

